---
os: linux
dist: xenial
language: ruby

env:
  global:
    secure: gbhfFSnxpYU4yviZTCJ7bjKuNpGEI0fnjKp+wROeaBgg8TAh0Ood/RwqcRWPT/OAsuuAtZS3gSrlMJYqzj2DOjP6ZiXRiQqTOcm1Onx6KpejFA9GXAKxC5H/JGikSpizwgSWQI6ZxqdkxB97UY03Gl6wNdIwMgynLVeBHlhv2PijTLAFrpbNtz/VtWm9FDppw3r6nEBKLK9GAThYHbicyvXVYgALLNQA56AJEPF2jGap+f1dERtzrUHl0/TD61uPyAd9GHKadbaff0tRKUl5pKX7vI8AOmiLEBAe0Legfm2uZWZUolEXpAWN0qwBkjPbgUwDVCABQayIPhNkec5ddKDMcUcTum67SdFRUH+4Bk0cnW7QlpTl5TgzXEizteYGPkuFmo+6ZStcrwCEJ1DgJSHKWQAS94X7LO3WZVyPdbH18K9KJgnfWNESwzR93Bor1AVRSSHk86VvHmfLALqR3yCnpVbGWzJZ5KnJASfDTjrFJOCTM72Sg6MFxsjg8enVmU3QxFEAIEdrOXNNsQmGcY25S0pi67JvoqOq26JUgwkCwl0V/pKhWToKUlT8gu+4yctS9CKSkwalljKu0oyeHlTPoyrvESVLhhyWbUrcKK/yRItH1J8b4K488UrTXmOH4HgaHE2ndNhXds1VDHSR1r+OBxyCEu7Mha3H4OHR8jw=

  jobs:
    - NODE_VERSION=12

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1

gemfile:
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_master.gemfile

addons:
  chrome: stable

cache:
  - bundler
  - yarn

before_install:
  # Install Node and JS dependencies
  - nvm install $NODE_VERSION
  - bin/yarn install

  # Install the Code Climate reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

  # Install the Chrome Driver for the installed version of Chrome
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
  - curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

  # Always use the latest versions of rubygems and bundler regardless of the Ruby version
  - gem update --system --no-doc
  - gem install bundler --no-doc

before_script:
  - ./cc-test-reporter before-build

after_script:
  # TODO: Also report JavaScript test coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false

  slack:
    rooms:
      secure: Sf5JqkbZU0IQ4cSUhEA+2uw7w6/HkuA2pUGg3/wEJGLMEeBKzTakpJR9esx8TmHLHg4h2TH5MD7EPhCJFhJ4zzLYmIOOwJpqBgnUKXl7HZ4yIseV0H7DWqmLAMDRVufQW8aGtanUD0UutR3CmQN1sqomJWDWovRS8ollSZ/4seuV5xaoVDABWVqppZVfeqbAOkE44xSXizQ97ORk0+2YbUahLmNgtwQBZtLFHo94USU4BFimm9zV8N3Ze0SDk8p991PI6q5R9n3+mNDapGl+5fjSpUw/wbGJ4fBC7ASu8esnQsAyTJ61T9krcX8XHT2lnxsNamrx9D83NOFuTfTteJv99m5EdzP+9eb3x1l1sk/sQfc9dum76Tf5Toe7aHTUOTDKdHPQazh4Cx293o+4UobieYP0+u99HFsznexX7jRYR0wb+0vzC825szzDS/msfvfAxflxMaFlhP2ZFCQcsKS1Z1m2yMcfNklcaskjiNYylTiwhVcq1L8wTydaHkBO2tcz8LYMxCATFMKtIODkklx75/8P1bVtlK6wT5p8yLnovUzQl1Hvk577y6v12yhYrW5QoBHoKd3qOyCO0pBsvOYCMXgvLlWf3nfD6PByw4Usz1Q2rQnBiGr2NGfuECUUp2OiTLJUUWnw8Loyz0Nq8ZRFMAlKte/QuC3I3LvfaSE=
    on_failure: always
    on_success: change # when fixed
    on_pull_requests: false
